name: FL4E
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - flwr==1.4.0
      - grpcio==1.51.1
      - lifelines
      - pandas=1.5.2
      - pyyaml==6.0
      - ray==2.2.0
      - torch==2.0.0
      - torchdata==0.6.0
      - torchvision==0.15.1
      - virtualenv==20.19.0
      - wandb==0.15.4
      - wget==3.2
      - yarl==1.8.2
